
var aHref="javascript://js";var Class2={create:function(){return function(){this.initialize.apply(this,arguments);}}}
var PopSelect=Class2.create();var AreaPopSelect=Class2.create();var AreaPopSelect4City=Class2.create();var AreaExpectPopSelect=Class2.create();var JobTypePopSelect=Class2.create();var PopCon=Class2.create();PopSelect.prototype={form:null,show:null,value:null,maxMun:null,title:null,tips:null,height:null,width:null,data:null,sender:null,fullText:null,defaultText:null,showByItem:null,topJQuery:top.jQuery,container:null,containerId:"pop_container",timmer:null,overlayId:"pop_overlay",overlay:null,initialize:function(args){var self=this;if("undefined"==typeof(args.show)||"undefined"==typeof(args.value)||"undefined"==typeof(args.data)||"undefined"==typeof(args.sender)){alert("@error in initialize, check args");}
this.form=args.form||"form1";this.show=args.show;this.value=args.value;this.maxMun=args.maxMun||5;this.data=args.data;this.title=args.title||"";this.tips=args.tips||"";this.sender=args.sender;this.width=args.width||400;this.defaultText=args.defaultText||"";this.height=args.height||510;if(typeof(args.fullText)=="undefined"){this.fullText=true;}else{this.fullText=args.fullText;}
if(typeof(args.showByItem)=="undefined"){this.showByItem=false;}else{this.showByItem=args.showByItem;}
if(typeof(args.chosen)!="undefined"){this.submitItemToItem(args.chosen);}
var sender=this.getItem(this.sender);sender.click(function(){self.display();});},getContainer:function(){if(null==this.container){if(this.topJQuery("#"+this.containerId).length==0){this.topJQuery("body").append("<div id=\""+this.containerId
+"\"></div>");}
this.container=this.topJQuery("#"+this.containerId);}
this.container.find(".boxwrap").css({width:this.width});return this.container;},getOverlay:function(){if(null==this.overlay){if(this.topJQuery("#"+this.overlayId).length==0){this.topJQuery("body").append("<iframe id=\""+this.overlayId
+"\" class=\"pop_overlayBG\"></iframe>");}
this.overlay=this.topJQuery("#"+this.overlayId);if(typeof(top.window.innerWidth)!='number'){this.overlay.css("height","0");this.overlay.css({"position":"absolute","height":this.topJQuery("body").get(0).scrollHeight});}}
return this.overlay;},display:function(){this._dispaly();this.getContainer().show();this.getOverlay().show();this.bindBigBox();},doSearchField:function(sf){var keyword=sf.value.replace(/\s+/g,"");var reg=new RegExp(keyword,"gi");var self=this;var value=jQuery("form[@name="+this.form+"] input[@name="
+this.value+"]");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var sel=jQuery.trim(value.val());var selArr=sel==""?[]:sel.split(",");var key;var value;var oItem;var oItems=Array();if(keyword==''){for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];if("00"==key.substr(2)){oItems.push(oItem);}}}else{for(var i=0;i<this.data.length;i++){oItem=this.data[i];value=oItem[1];if(value.replace(reg,"")!=value){oItems.push(oItem);}}}
var htmlLine=new Array();var className="";for(var i=0;i<oItems.length;i++){oItem=oItems[i];className=self.hasChild(oItem[0])?"":'class="noico"';htmlLine.push('<li no='+oItem[0]+'><a href="'+aHref+'" '
+className+'><input type="checkbox" /> '
+oItem[1].substring(0,35)+' </a></li>');}
var bigBox=this.getContainer().find(".multiBoxOptions");bigBox.html("<ul>"+htmlLine.join("\n")+"</ul>");bigBox.find("li").unbind("mouseover").mouseover(function(event){if(self.timmer!=null){clearTimeout(self.timmer);}
var no=jQuery(this).attr("no");self.timmer=setTimeout(function(){self.overBigItem(no,event);},300);}).unbind("mouseout").mouseout(function(){if(self.timmer!=null){clearTimeout(self.timmer);}
self.timmer=setTimeout(function(){self.getContainer().find(".boxiiOptions").hide();},100);}).unbind("click").click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().parent().attr("no"));}).find("input[@type=checkbox]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});this.getContainer().find("[@name=select_value]").val(sel);for(var i=0;i<selArr.length;i++){if(selArr[i]==""){continue;}
this.getContainer().find("li[@no="+selArr[i]+"]").find("input[@type=checkbox]").attr("checked",true);var text=this.getFunText(selArr[i]);this.getContainer().find(".tipsmaintop ul").append('<li no='
+selArr[i]+'><a href="'+aHref+'" title="点击删除">'
+text+'</a></li>').find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".multiBoxOptions , .boxiiOptions").find("li[@no="+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@type=checkbox]").attr("checked",false);}
self.clickItem(srcNo);});}
this.displayTips();},bindBigBox:function(){var self=this;var value=jQuery("form[@name="+this.form+"] input[@name="
+this.value+"]");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var sel=jQuery.trim(value.val());var selArr=sel==""?[]:sel.split(",");var key;var value;var oItem;var oItems=Array();for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];if("00"==key.substr(2)){oItems.push(oItem);}}
var htmlLine=new Array();var className="";for(var i=0;i<oItems.length;i++){oItem=oItems[i];className=self.hasChild(oItem[0])?"":'class="noico"';htmlLine.push('<li no='+oItem[0]+'><a href="'+aHref+'" '
+className+'><input type="checkbox" /> '
+oItem[1].substring(0,35)+' </a></li>');}
var bigBox=this.getContainer().find(".multiBoxOptions");bigBox.html("<ul>"+htmlLine.join("\n")+"</ul>");bigBox.find("li").unbind("mouseover").mouseover(function(event){if(self.timmer!=null){clearTimeout(self.timmer);}
var no=jQuery(this).attr("no");self.timmer=setTimeout(function(){self.overBigItem(no,event);},300);}).unbind("mouseout").mouseout(function(){if(self.timmer!=null){clearTimeout(self.timmer);}
self.timmer=setTimeout(function(){self.getContainer().find(".boxiiOptions").hide();},100);}).unbind("click").click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().parent().attr("no"));}).find("input[@type=checkbox]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});this.getContainer().find("[@name=select_value]").val(sel);for(var i=0;i<selArr.length;i++){if(selArr[i]==""){continue;}
this.getContainer().find("li[@no="+selArr[i]+"]").find("input[@type=checkbox]").attr("checked",true);var text=this.getFunText(selArr[i]);this.getContainer().find(".tipsmaintop ul").append('<li no='
+selArr[i]+'><a href="'+aHref+'" title="点击删除">'
+text+'</a></li>').find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".multiBoxOptions , .boxiiOptions").find("li[@no="+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@type=checkbox]").attr("checked",false);}
self.clickItem(srcNo);});}
this.displayTips();var searchField=this.getContainer().find("#searchField");searchField.unbind("keyup").keyup(function(){self.doSearchField(this)})},overBigItem:function(itemNo,event){var self=this;var key=itemNo.substr(0,2);var oItems=new Array();var htmlLine=new Array();var smallBox=this.getContainer().find(".boxiiOptions");if(this.getContainer().find(".multiBoxOptions li[@no="+itemNo
+"] a").attr("class")=="noico"){smallBox.hide();return;}
var oItem;for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0].substr(0,2)==key){if(oItem[0]==itemNo){continue;}
oItems.push(oItem);}}
for(var i=0;i<oItems.length;i++){oItem=oItems[i];htmlLine.push('<li no='+oItem[0]+'><a href="'+aHref
+'" title="'+oItem[1]+'"><input type="checkbox" /> '
+oItem[1].substring(0,25)+' </a></li>');}
smallBox.html("<ul>"+htmlLine.join("\n")+"</ul>");smallBox.find("li").mouseout(function(){if(self.timmer!=null){clearTimeout(self.timmer);}
self.timmer=setTimeout(function(){smallBox.hide();},100);}).unbind("mouseover").mouseover(function(event){if(self.timmer!=null){clearTimeout(self.timmer);}}).unbind("click").click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().parent().attr("no"));}).find("input[@type=checkbox]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});var bigBox=this.getContainer().find(".multiBoxOptions");var bChecked=bigBox.find("li[@no="+itemNo
+"] input[@type=checkbox]").attr("checked");if(bChecked){smallBox.find("li").unbind("click").end().find("input[@type=checkbox]").unbind("click").attr("checked",true).attr("disabled",true);}else{var selVal=this.getContainer().find("[@name=select_value]").val();var selArr=selVal.split(",");for(var i=0;i<selArr.length;i++){smallBox.find("li[@no="+selArr[i]+"] input[@type=checkbox]").attr("checked",true);}}
var sender=event.currentTarget||event.srcElement;sender=jQuery(sender);try{var wSize=this.windowSize();var top=sender.offset().top
var left=null;if(sender.offset().left
-this.getContainer().find(".multiBoxOptions").offset().left<200){left=sender.offset().left+sender.width();}else{left=sender.offset().left-smallBox.width();}
if(top+smallBox.height()>(wSize[1]+self.getScrollTop())){top=wSize[1]+self.getScrollTop()-smallBox.height();}
smallBox.css("top",top).css("left",left).show();}catch(e){}},_dispaly:function(){var self=this;var html="";html+='<div class="boxwrap">';html+=' <h3>';html+='  <span><a href="'+aHref+'" id="close" title="关闭"></a>';html+='  </span>'+this.title;html+=' </h3>';html+=' <div class="boxinwrap">';html+='  <!--弹出层开始 -->';html+='  <div class="box">';html+='   <!--顶部开始 -->';html+='   <div class="boxheader">';html+='    <!--提示开始 -->';html+='    <div class="tips">';html+='      <span>';html+='       <input type="button" name="sub" value="确定" />';html+='      <input name="select_value" type="hidden" />';html+='      <input type="button" name="cls" value="清空" />';html+='   </span>';html+=' &nbsp;&nbsp;<font color=red>筛选关键字：</font><input type="text" name="searchField" id="searchField" size="15"/>   </div>';html+='    <!--提示开始 -->';html+='    <!--结果开始 -->';html+='    <div class="tipsmaintop">';html+='     <p>';html+='      符号＂';html+='      <img src="'+basePath
+'images/ico.gif" align="middle" />';html+='      ＂下的含具体选项';html+='      <br />';html+='      您最多可以选择'+self.maxMun+'个选项';html+='     </p>';html+='     <ul></ul>';html+='    </div>';html+='    <!--结果结束 -->';html+='   </div>';html+='   <!--顶部结束 -->';html+='   <!--选项开始 -->';html+='   <div class="multiBoxOptions">';html+='   </div>';html+='   <!--选项结束 -->';html+='  </div>';html+='  <!--弹出层结束 -->';html+=' </div>';html+='</div>';html+='<!--二级选项开始 -->';html+='<div class="boxiiOptions" style="display:none">';html+='</div>';html+='<!--二级选项结束 -->';this.getContainer().html(html);var wSize=this.windowSize();var left=wSize[0]/2-this.getContainer().find(".boxwrap").width()/2;this.getContainer().find(".boxwrap").css("left",left);this.getContainer().find(".boxwrap").css("top",self.getScrollTop()+60);this.getContainer().find("[@name=sub]").click(function(){self.submitItem();});this.getContainer().find("[@name=cls]").click(function(){self.clearItem();});this.getContainer().find("#close").click(function(){self.remove();});},submitItem:function(){if(this.showByItem){this.submitItemToItem();}else{this.submitItemToInput();}},submitItemToInput:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var showText="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
showText+=text+" ";}}
if(showText==""){showText+=this.defaultText;}
show.val(jQuery.trim(showText));this.remove();},submitItemToItem:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var html="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
html+='<div><span>'+text
+'</span><a title="点击删除" href="javascript://" no="'
+valArr[i]+'">X</a></div>';}}
if(html==""){html+='<div><span>'+this.defaultText+'</span></div>';}
show.html(html);show.find("a").hover(function(){self.itemMoveOver(this);},function(){self.itemMoveOut(this);}).click(function(){self.itemDelete(this);});this.remove();},itemMoveOver:function(sender){sender=jQuery(sender);var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");show.find("div").removeClass();sender.parent().addClass("pop_widhtDIVBG");},itemMoveOut:function(sender){sender=jQuery(sender);sender.parent().removeClass();},itemDelete:function(sender){sender=jQuery(sender);var no=sender.attr("no");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var val=value.val();val=val.replace(no,"");val=val.replace(/\,+/g,",");if(val.substr(val.length-1)==","){val=val.substr(0,val.length-1);}
value.val(val);sender.parent().remove();var show=form.find("[@name="+this.show+"]");if(show.html()==""){show.html("<div>&nbsp;</div>")}},clearItem:function(){var self=this;var selectedItem=this.getContainer().find(".tipsmaintop");var selectValue=this.getContainer().find("[@name=select_value]");selectValue.val("");selectedItem.find("li").remove();this.getContainer().find(".multiBoxOptions input[@type=checkbox]").attr("checked",false).attr("disabled",false);this.getContainer().find(".boxiiOptions input[@type=checkbox]").attr("checked",false).attr("disabled",false);this.getContainer().find(".tipsmaintop p").show();},clickItem:function(itemNo){var self=this;var sender=this.getContainer().find(".multiBoxOptions , .boxiiOptions").find("li[@no="
+itemNo+"]");var checkbox=sender.find("input[@type=checkbox]");var isChecked=checkbox.length>0?checkbox.attr("checked"):false;var selectValue=this.getContainer().find("[@name=select_value]");var selectedItem=this.getContainer().find(".tipsmaintop ul");if(isChecked&&selectedItem.find("li").length>=this.maxMun){alert("对不起，您只能选择"+this.maxMun+"项");checkbox.attr("checked",false);return;}
if(isChecked){if(selectedItem.find("li[@no="+itemNo+"]").length==0){var text=this.getFunText(itemNo);selectedItem.append('<li no='+itemNo+'><a href="'+aHref
+'" title="点击删除">'+text+'</a></li>');selectedItem.find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".multiBoxOptions , .boxiiOptions").find("li[@no="+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@type=checkbox]").attr("checked",false);}
self.clickItem(srcNo);});}
if(selectValue.val().indexOf(itemNo)==-1){var val=selectValue.val();val+=val==""?"":",";val+=itemNo;selectValue.val(val);}
if(itemNo.substr(2)=="00"){selectedItem.find("li[@no^="+itemNo.substr(0,2)+"]").not("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());var tmp=val.split(",");var valArr=new Array();for(var i=0;i<tmp.length;i++){if(tmp[i]==""){continue;}
if(tmp[i].substr(0,2)==itemNo.substr(0,2)){if(tmp[i]!=itemNo){continue;}}
valArr.push(tmp[i]);}
selectValue.val(valArr.join(","));}}else{selectedItem.find("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());val=val.replace(itemNo,"");val=val.replace(/,+/g,",");if(","==val)
val="";selectValue.val(val);}
this.displayTips();if(self.maxMun==1){if(selectedItem.find("li").length==1){self.submitItem();}}
if(itemNo.substr(2)=="00"){var smallBox=this.getContainer().find(".boxiiOptions");var smallItem=smallBox.find("li").eq(0);if(smallItem.length!=0){if(smallItem.attr("no").substr(0,2)==itemNo.substr(0,2)){var smallItems=smallBox.find("li");smallItems.find("input[@type=checkbox]").attr("checked",isChecked).attr("disabled",isChecked);if(isChecked){smallItems.unbind("click");}else{smallItems.click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().parent().attr("no"));});}}}}},displayTips:function(){if(this.getContainer().find(".tipsmaintop li").length>0){this.getContainer().find(".tipsmaintop p").hide();}else{this.getContainer().find(".tipsmaintop p").show();}},remove:function(){this.getContainer().remove();this.container=null;this.getOverlay().remove();this.overlay=null;},hasChild:function(itemNo){if(itemNo.substr(2)!=00){return false;}
var oItem;var key=itemNo.substr(0,2);for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0].substr(0,2)!=key){continue;}
if(itemNo!=oItem[0]){return true;}}
return false;},getFunText:function(itemNo){var text="";for(var i=0;i<this.data.length;i++){var key=itemNo.substr(0,2);if(this.data[i][0].substr(0,2)==key){if(this.data[i][0].substr(2)=="00"){text+=this.data[i][1];if(itemNo==this.data[i][0]){return text;}
text+="-";}else{if(this.data[i][0]==itemNo){text+=this.data[i][1];return text;}}}}},windowSize:function(){var wWidth=0,wHeight=0;if(typeof(top.window.innerWidth)=='number'){wWidth=top.window.innerWidth;wHeight=top.window.innerHeight;}else if(top.document.documentElement&&(top.document.documentElement.clientWidth||top.document.documentElement.clientHeight)){wWidth=top.document.documentElement.clientWidth;wHeight=top.document.documentElement.clientHeight;}else if(top.document.body&&(top.document.body.clientWidth||top.document.body.clientHeight)){wWidth=top.document.body.clientWidth;wHeight=top.document.body.clientHeight;}
return[wWidth,wHeight];},getScrollTop:function(){return top.document.body.scrollTop>0?top.document.body.scrollTop:top.document.documentElement.scrollTop;},getItem:function(name){var _item=jQuery("#"+name);if(_item.length==0){_item=jQuery("[@name="+name+"]").eq(0);}
return _item;}};AreaPopSelect.prototype={form:null,show:null,value:null,maxMun:null,title:null,tips:null,height:null,width:null,data:null,sender:null,fullText:null,defaultText:null,showByItem:null,topJQuery:top.jQuery,container:null,containerId:"pop_container",overlayId:"pop_overlay",overlay:null,initialize:function(args){var self=this;if("undefined"==typeof(args.show)||"undefined"==typeof(args.value)||"undefined"==typeof(args.data)||"undefined"==typeof(args.sender)){alert("@error in initialize, check args");}
this.form=args.form||"form1";this.show=args.show;this.value=args.value;this.maxMun=args.maxMun||5;this.data=args.data;this.title=args.title||"";this.tips=args.tips||"";this.sender=args.sender;this.width=args.width||400;this.defaultText=args.defaultText||"";this.height=args.height||510;if(typeof(args.fullText)=="undefined"){this.fullText=true;}else{this.fullText=args.fullText;}
if(typeof(args.showByItem)=="undefined"){this.showByItem=false;}else{this.showByItem=args.showByItem;}
if(typeof(args.chosen)!="undefined"){this.submitItemToItem(args.chosen);}
var sender=this.getItem(this.sender);sender.click(function(){self.display();});},getContainer:function(){if(null==this.container){if(this.topJQuery("#"+this.containerId).length==0){this.topJQuery("body").append("<div id=\""+this.containerId
+"\"></div>");}
this.container=this.topJQuery("#"+this.containerId);}
this.container.find(".boxwrap").css({width:this.width});return this.container;},getOverlay:function(){if(null==this.overlay){if(this.topJQuery("#"+this.overlayId).length==0){this.topJQuery("body").append("<iframe id=\""+this.overlayId
+"\" class=\"pop_overlayBG\"></iframe>");}
this.overlay=this.topJQuery("#"+this.overlayId);if(typeof(top.window.innerWidth)!='number'){this.overlay.css("height","0");this.overlay.css({"position":"absolute","height":this.topJQuery("body").get(0).scrollHeight});}}
return this.overlay;},display:function(){this._dispaly();this.getContainer().show();this.getOverlay().show();this.bindBigBox();},bindBigBox:function(){var self=this;var value=jQuery("form[@name="+this.form+"] input[@name="
+this.value+"]");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var sel=jQuery.trim(value.val());var selArr=sel==""?[]:sel.split(",");var key;var value;var oItem;var oItems=Array();for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];if("00"==key.substr(2)){oItems.push(oItem);}}
var htmlLine=new Array();var className="";for(var i=0;i<oItems.length;i++){oItem=oItems[i];className="class='noico'";htmlLine.push('<li no='
+oItem[0]
+'><a href="'
+aHref
+'" '
+className
+'>'
+oItem[1]
+'<input name="check_value" type="hidden" value="false"/></a></li>');}
var bigBox=this.getContainer().find(".singleBoxOptions");bigBox.html('<div>所有省份</div><ul>'+htmlLine.join("\n")+'</ul>');bigBox.find("li").unbind("click").click(function(event){var no=jQuery(this).attr("no");var temp=new Array("1100","1000","1200","1300","4100","4200","4300","4400","4500");for(var i=0;i<temp.length;i++){if(temp[i]==no){var check=jQuery(this).find("input[@name=check_value]");self.clickItem(check.parent().parent().attr("no"));return;}}
self.overBigItem(no,event);}).find("input[@name=check_value]").unbind("click").click(function(event){var no=jQuery(this).attr("no");var temp=new Array("1100","1000","1200","1300","4100","4200","4300","4400","4500");for(var i=0;i<temp.length;i++){if(temp[i]==no){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();return;}}
self.overBigItem(no,event);event.stopPropagation();});this.getContainer().find("[@name=select_value]").val(sel);for(var i=0;i<selArr.length;i++){if(selArr[i]==""){continue;}
this.getContainer().find("li[@no="+selArr[i]+"]").find("input[@name=check_value]").val("true");var text=this.getFunText(selArr[i]);this.getContainer().find(".tipsmaintop ul").html("");this.getContainer().find(".tipsmaintop ul").append('<li no='
+selArr[i]+'><a href="'+aHref+'" title="点击删除">'
+text+'</a></li>').find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".singleBoxOptions").find("li[@no="
+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@name=check_value]").val("false");}
self.clearItem();});}
this.displayTips();},overBigItem:function(itemNo,event){var itemName;var self=this;var key=itemNo.substr(0,2);var oItems=new Array();var htmlLine=new Array();var selectedItem=this.getContainer().find(".singleBoxOptions");var oItem;for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0]==itemNo){itemName=oItem[1];}
if(oItem[0].substr(0,2)==key){if(oItem[0]==itemNo){continue;}
oItems.push(oItem);}}
var className="class=noico";for(var i=0;i<oItems.length;i++){oItem=oItems[i];htmlLine.push('<li no='
+oItem[0]
+'><a href="'
+aHref
+'"'
+className
+'>'
+oItem[1]
+'<input name="check_value" type="hidden" value="false"/></a></li>');}
selectedItem.html('<div>'+itemName+'&nbsp;&nbsp;&nbsp;<a href="'
+aHref+'">'+'[返回所有省份]</a></div><ul>'+htmlLine.join('\n')
+'</ul>');selectedItem.find("div a").unbind("click").click(function(){self.bindBigBox();});selectedItem.find("li").unbind("click").click(function(){var check=jQuery(this).find("input[@name=check_value]");check.val(!check.val());self.clickItem(check.parent().parent().attr("no"));}).find("input[@name=check_value]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});},_dispaly:function(){var self=this;var html="";html+='<div class="boxwrap">';html+=' <h3>';html+='  <span><a href="'+aHref+'" id="close" title="关闭"></a>';html+='  </span>'+this.title;html+=' </h3>';html+=' <div class="boxinwrap">';html+='  <!--弹出层开始 -->';html+='  <div class="box">';html+='   <!--顶部开始 -->';html+='   <div class="boxheader">';html+='    <!--提示开始 -->';html+='    <div class="tips">';html+='     <span>';html+='      <input type="button" name="sub" value="确定" />';html+='      <input name="select_value" type="hidden" />';html+='      <input type="button" name="cls" value="清空" />';html+='     </span>提示：';html+='    </div>';html+='    <!--提示开始 -->';html+='    <!--结果开始 -->';html+='    <div class="tipsmaintop">';html+='     <p>';html+='      您最多可以选择'+self.maxMun+'个选项';html+='     </p>';html+='     <ul></ul>';html+='    </div>';html+='    <!--结果结束 -->';html+='   </div>';html+='   <!--顶部结束 -->';html+='   <!--选项开始 -->';html+='   <div class="singleBoxOptions">';html+='   </div>';html+='   <!--选项结束 -->';html+='  </div>';html+='  <!--弹出层结束 -->';html+=' </div>';html+='</div>';html+='<!--二级选项开始 -->';html+='<div class="boxiiOptions" style="display:none">';html+='</div>';html+='<!--二级选项结束 -->';this.getContainer().html(html);var wSize=this.windowSize();var left=wSize[0]/2-this.getContainer().find(".boxwrap").width()/2;this.getContainer().find(".boxwrap").css("left",left);this.getContainer().find(".boxwrap").css("top",self.getScrollTop()+60);this.getContainer().find("[@name=sub]").click(function(){self.submitItem();});this.getContainer().find("[@name=cls]").click(function(){self.clearItem();});this.getContainer().find("#close").click(function(){self.remove();});},submitItem:function(){if(this.showByItem){this.submitItemToItem();}else{this.submitItemToInput();}},submitItemToInput:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var showText="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
showText+=text+" ";}}
if(showText==""){showText+=this.defaultText;}
show.val(jQuery.trim(showText));this.remove();},submitItemToItem:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var html="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
html+='<div><span>'+text
+'</span><a title="点击删除" href="javascript://" no="'
+valArr[i]+'">X</a></div>';}}
if(html==""){html+='<div><span>'+this.defaultText+'</span></div>';}
show.html(html);show.find("a").hover(function(){self.itemMoveOver(this);},function(){self.itemMoveOut(this);}).click(function(){self.itemDelete(this);});this.remove();},itemMoveOver:function(sender){sender=jQuery(sender);var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");show.find("div").removeClass();sender.parent().addClass("pop_widhtDIVBG");},itemMoveOut:function(sender){sender=jQuery(sender);sender.parent().removeClass();},itemDelete:function(sender){sender=jQuery(sender);var no=sender.attr("no");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var val=value.val();val=val.replace(no,"");val=val.replace(/\,+/g,",");if(val.substr(val.length-1)==","){val=val.substr(0,val.length-1);}
value.val(val);sender.parent().remove();var show=form.find("[@name="+this.show+"]");if(show.html()==""){show.html("<div>&nbsp;</div>")}},clearItem:function(){var self=this;var selectedItem=this.getContainer().find(".tipsmaintop");var selectValue=this.getContainer().find("[@name=select_value]");selectValue.val("");selectedItem.find("li").remove();this.getContainer().find(".singleBoxOptions input[@name=check_value]").val("false").attr("disabled",false);this.getContainer().find(".tipsmaintop p").show();},clickItem:function(itemNo){var self=this;var sender=this.getContainer().find(".singleBoxOptions").find("li[@no="+itemNo+"]");var a=sender.find("a");var checkbox=this.getContainer().find("input[@name=check_value]");var isChecked=checkbox.val()=="false"?true:false;var selectValue=this.getContainer().find("[@name=select_value]");var selectedItem=this.getContainer().find(".tipsmaintop ul");if(isChecked&&selectedItem.find("li").length>=this.maxMun){alert("对不起，您只能选择"+this.maxMun+"项");this.getContainer().find("input[@name=check_value]").val("false");return;}
if(isChecked){if(selectedItem.find("li[@no="+itemNo+"]").length==0){var text=this.getFunText(itemNo);selectedItem.append('<li no='+itemNo+'><a href="'+aHref
+'" title="点击删除">'+text+'</a></li>');selectedItem.find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".singleBoxOptions").find("li[@no="+srcNo
+"]");if(srcSendr.length>=0){srcSendr.find("input[@name=check_value]").val("false");}
self.clickItem(srcNo);});}
if(selectValue.val().indexOf(itemNo)==-1){var val=selectValue.val();val+=val==""?"":",";val+=itemNo;selectValue.val(val);}
if(itemNo.substr(2)=="00"){selectedItem.find("li[@no^="+itemNo.substr(0,2)+"]").not("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());var tmp=val.split(",");var valArr=new Array();for(var i=0;i<tmp.length;i++){if(tmp[i]==""){continue;}
if(tmp[i].substr(0,2)==itemNo.substr(0,2)){if(tmp[i]!=itemNo){continue;}}
valArr.push(tmp[i]);}
selectValue.val(valArr.join(","));}}else{selectedItem.find("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());val=val.replace(itemNo,"");val=val.replace(/,+/g,",");if(","==val)
val="";selectValue.val(val);}
this.displayTips();if(self.maxMun==1){if(selectedItem.find("li").length==1){self.submitItem();}}
if(itemNo.substr(2)=="00"){var selectedItem=this.getContainer().find(".tipsmaintop ul");var smallItem=selectedItem.find("li").eq(0);if(smallItem.length!=0){if(smallItem.attr("no").substr(0,2)==itemNo.substr(0,2)){var smallItems=selectedItem.find("li");smallItems.find("input[@name=check_value]").val(isChecked).attr("disabled",isChecked);if(isChecked){smallItems.unbind("click");}else{smallItems.click(function(){var checkbox=jQuery(this).find("input[@name=check_value]");checkbox.attr(!checkbox.val());self.clickItem(checkbox.parent().parent().attr("no"));});}}}}},displayTips:function(){if(this.getContainer().find(".tipsmaintop li").length>0){this.getContainer().find(".tipsmaintop p").hide();}else{this.getContainer().find(".tipsmaintop p").show();}},remove:function(){this.getContainer().remove();this.container=null;this.getOverlay().remove();this.overlay=null;},hasChild:function(itemNo){if(itemNo.substr(2)!=00){return false;}
var oItem;var key=itemNo.substr(0,2);for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0].substr(0,2)!=key){continue;}
if(itemNo!=oItem[0]){return true;}}
return false;},getFunText:function(itemNo){var text="";for(var i=0;i<this.data.length;i++){var key=itemNo.substr(0,2);if(this.data[i][0].substr(0,2)==key){if(this.data[i][0].substr(2)=="00"){text+=this.data[i][1];if(itemNo==this.data[i][0]){return text;}
text+="-";}else{if(this.data[i][0]==itemNo){text+=this.data[i][1];return text;}}}}},windowSize:function(){var wWidth=0,wHeight=0;if(typeof(top.window.innerWidth)=='number'){wWidth=top.window.innerWidth;wHeight=top.window.innerHeight;}else if(top.document.documentElement&&(top.document.documentElement.clientWidth||top.document.documentElement.clientHeight)){wWidth=top.document.documentElement.clientWidth;wHeight=top.document.documentElement.clientHeight;}else if(top.document.body&&(top.document.body.clientWidth||top.document.body.clientHeight)){wWidth=top.document.body.clientWidth;wHeight=top.document.body.clientHeight;}
return[wWidth,wHeight];},getScrollTop:function(){return top.document.body.scrollTop>0?top.document.body.scrollTop:top.document.documentElement.scrollTop;},getItem:function(name){var _item=jQuery("#"+name);if(_item.length==0){_item=jQuery("[@name="+name+"]").eq(0);}
return _item;}};AreaPopSelect4City.prototype={form:null,show:null,value:null,maxMun:null,title:null,tips:null,height:null,width:null,data:null,sender:null,fullText:null,defaultText:null,showByItem:null,topJQuery:top.jQuery,container:null,containerId:"pop_container",overlayId:"pop_overlay",overlay:null,initialize:function(args){var self=this;if("undefined"==typeof(args.show)||"undefined"==typeof(args.value)||"undefined"==typeof(args.data)||"undefined"==typeof(args.sender)){alert("@error in initialize, check args");}
this.form=args.form||"form1";this.show=args.show;this.value=args.value;this.maxMun=args.maxMun||5;this.data=args.data;this.title=args.title||"";this.tips=args.tips||"";this.sender=args.sender;this.width=args.width||400;this.defaultText=args.defaultText||"";this.height=args.height||510;if(typeof(args.fullText)=="undefined"){this.fullText=true;}else{this.fullText=args.fullText;}
if(typeof(args.showByItem)=="undefined"){this.showByItem=false;}else{this.showByItem=args.showByItem;}
if(typeof(args.chosen)!="undefined"){this.submitItemToItem(args.chosen);}
var sender=this.getItem(this.sender);sender.click(function(){self.display();});},getContainer:function(){if(null==this.container){if(this.topJQuery("#"+this.containerId).length==0){this.topJQuery("body").append("<div id=\""+this.containerId
+"\"></div>");}
this.container=this.topJQuery("#"+this.containerId);}
this.container.find(".boxwrap").css({width:this.width});return this.container;},getOverlay:function(){if(null==this.overlay){if(this.topJQuery("#"+this.overlayId).length==0){this.topJQuery("body").append("<iframe id=\""+this.overlayId
+"\" class=\"pop_overlayBG\"></iframe>");}
this.overlay=this.topJQuery("#"+this.overlayId);if(typeof(top.window.innerWidth)!='number'){this.overlay.css("height","0");this.overlay.css({"position":"absolute","height":this.topJQuery("body").get(0).scrollHeight});}}
return this.overlay;},display:function(){this._dispaly();this.getContainer().show();this.getOverlay().show();this.bindBigBox();},bindBigBox:function(){var self=this;var value=jQuery("form[@name="+this.form+"] input[@name="
+this.value+"]");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var sel=jQuery.trim(value.val());var selArr=sel==""?[]:sel.split(",");var key;var value;var oItem;var oItems=Array();for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];if("00"==key.substr(2)){oItems.push(oItem);}}
var htmlLine=new Array();var className="";for(var i=0;i<oItems.length;i++){oItem=oItems[i];className="class='noico'";htmlLine.push('<li no='
+oItem[0]
+'><a href="'
+aHref
+'" '
+className
+'>'
+oItem[1]
+'<input name="check_value" type="hidden" value="false"/></a></li>');}
var bigBox=this.getContainer().find(".singleBoxOptions");bigBox.html('<div>所有省份</div><ul>'+htmlLine.join("\n")+'</ul>');bigBox.find("li").unbind("click").click(function(event){var no=jQuery(this).attr("no");var temp=new Array("1100","1000","1200","1300","4100","4200","4300","4400","4500");for(var i=0;i<temp.length;i++){if(temp[i]==no){var check=jQuery(this).find("input[@name=check_value]");self.clickItem(check.parent().parent().attr("no"));return;}}
self.overBigItem(no,event);}).find("input[@name=check_value]").unbind("click").click(function(event){var no=jQuery(this).attr("no");var temp=new Array("1100","1000","1200","1300","4100","4200","4300","4400","4500");for(var i=0;i<temp.length;i++){if(temp[i]==no){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();return;}}
self.overBigItem(no,event);event.stopPropagation();});this.getContainer().find("[@name=select_value]").val(sel);for(var i=0;i<selArr.length;i++){if(selArr[i]==""){continue;}
this.getContainer().find("li[@no="+selArr[i]+"]").find("input[@name=check_value]").val("true");var text=this.getFunText(selArr[i]);this.getContainer().find(".tipsmaintop ul").html("");this.getContainer().find(".tipsmaintop ul").append('<li no='
+selArr[i]+'><a href="'+aHref+'" title="点击删除">'
+text+'</a></li>').find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".singleBoxOptions").find("li[@no="
+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@name=check_value]").val("false");}
self.clearItem();});}
this.displayTips();},overBigItem:function(itemNo,event){var itemName;var self=this;var key=itemNo.substr(0,2);var oItems=new Array();var htmlLine=new Array();var selectedItem=this.getContainer().find(".singleBoxOptions");var oItem;for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0]==itemNo){itemName=oItem[1];}
if(oItem[0].substr(0,2)==key){if(oItem[0]==itemNo){continue;}
oItems.push(oItem);}}
var className="class=noico";for(var i=0;i<oItems.length;i++){oItem=oItems[i];htmlLine.push('<li no='
+oItem[0]
+'><a href="'
+aHref
+'"'
+className
+'>'
+oItem[1]
+'<input name="check_value" type="hidden" value="false"/></a></li>');}
selectedItem.html('<div>'+itemName+'&nbsp;&nbsp;&nbsp;<a href="'
+aHref+'">'+'[返回所有省份]</a></div><ul>'+htmlLine.join('\n')
+'</ul>');selectedItem.find("div a").unbind("click").click(function(){self.bindBigBox();});selectedItem.find("li").unbind("click").click(function(){var check=jQuery(this).find("input[@name=check_value]");check.val(!check.val());self.clickItem(check.parent().parent().attr("no"));}).find("input[@name=check_value]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});},_dispaly:function(){var self=this;var html="";html+='<div class="boxwrap">';html+=' <h3>';html+='  <span><a href="'+aHref+'" id="close" title="关闭"></a>';html+='  </span>'+this.title;html+=' </h3>';html+=' <div class="boxinwrap">';html+='  <!--弹出层开始 -->';html+='  <div class="box">';html+='   <!--顶部开始 -->';html+='   <div class="boxheader">';html+='    <!--提示开始 -->';html+='    <div class="tips">';html+='     <span>';html+='      <input type="button" name="sub" value="确定" />';html+='      <input name="select_value" type="hidden" />';html+='      <input type="button" name="cls" value="清空" />';html+='     </span>提示：';html+='    </div>';html+='    <!--提示开始 -->';html+='    <!--结果开始 -->';html+='    <div class="tipsmaintop">';html+='     <p>';html+='      您最多可以选择'+self.maxMun+'个选项';html+='     </p>';html+='     <ul></ul>';html+='    </div>';html+='    <!--结果结束 -->';html+='   </div>';html+='   <!--顶部结束 -->';html+='   <!--选项开始 -->';html+='   <div class="singleBoxOptions">';html+='   </div>';html+='   <!--选项结束 -->';html+='  </div>';html+='  <!--弹出层结束 -->';html+=' </div>';html+='</div>';html+='<!--二级选项开始 -->';html+='<div class="boxiiOptions" style="display:none">';html+='</div>';html+='<!--二级选项结束 -->';this.getContainer().html(html);var wSize=this.windowSize();var left=wSize[0]/2-this.getContainer().find(".boxwrap").width()/2;this.getContainer().find(".boxwrap").css("left",left);this.getContainer().find(".boxwrap").css("top",self.getScrollTop()+60);this.getContainer().find("[@name=sub]").click(function(){self.submitItem();});this.getContainer().find("[@name=cls]").click(function(){self.clearItem();});this.getContainer().find("#close").click(function(){self.remove();});},submitItem:function(){if(this.showByItem){this.submitItemToItem();}else{this.submitItemToInput();}},submitItemToInput:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");var sFeatures="height=600, width=810, top=0, left=0, toolbar=no, menubar=no, scrollbars=yes, resizable=yes,location=no, status=yes";if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
for(var i=0;i<this.data.length;i++){if(this.data[i][0]==val){var url='city.do?city='+this.data[i][2];window.open(url);this.getContainer().hide();break;}}},submitItemToItem:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var html="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
html+='<div><span>'+text
+'</span><a title="点击删除" href="javascript://" no="'
+valArr[i]+'">X</a></div>';}}
if(html==""){html+='<div><span>'+this.defaultText+'</span></div>';}
show.html(html);show.find("a").hover(function(){self.itemMoveOver(this);},function(){self.itemMoveOut(this);}).click(function(){self.itemDelete(this);});this.remove();},itemMoveOver:function(sender){sender=jQuery(sender);var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");show.find("div").removeClass();sender.parent().addClass("pop_widhtDIVBG");},itemMoveOut:function(sender){sender=jQuery(sender);sender.parent().removeClass();},itemDelete:function(sender){sender=jQuery(sender);var no=sender.attr("no");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var val=value.val();val=val.replace(no,"");val=val.replace(/\,+/g,",");if(val.substr(val.length-1)==","){val=val.substr(0,val.length-1);}
value.val(val);sender.parent().remove();var show=form.find("[@name="+this.show+"]");if(show.html()==""){show.html("<div>&nbsp;</div>")}},clearItem:function(){var self=this;var selectedItem=this.getContainer().find(".tipsmaintop");var selectValue=this.getContainer().find("[@name=select_value]");selectValue.val("");selectedItem.find("li").remove();this.getContainer().find(".singleBoxOptions input[@name=check_value]").val("false").attr("disabled",false);this.getContainer().find(".tipsmaintop p").show();},clickItem:function(itemNo){var self=this;var sender=this.getContainer().find(".singleBoxOptions").find("li[@no="+itemNo+"]");var a=sender.find("a");var checkbox=this.getContainer().find("input[@name=check_value]");var isChecked=checkbox.val()=="false"?true:false;var selectValue=this.getContainer().find("[@name=select_value]");var selectedItem=this.getContainer().find(".tipsmaintop ul");if(isChecked&&selectedItem.find("li").length>=this.maxMun){alert("对不起，您只能选择"+this.maxMun+"项");this.getContainer().find("input[@name=check_value]").val("false");return;}
if(isChecked){if(selectedItem.find("li[@no="+itemNo+"]").length==0){var text=this.getFunText(itemNo);selectedItem.append('<li no='+itemNo+'><a href="'+aHref
+'" title="点击删除">'+text+'</a></li>');selectedItem.find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".singleBoxOptions").find("li[@no="+srcNo
+"]");if(srcSendr.length>=0){srcSendr.find("input[@name=check_value]").val("false");}
self.clickItem(srcNo);});}
if(selectValue.val().indexOf(itemNo)==-1){var val=selectValue.val();val+=val==""?"":",";val+=itemNo;selectValue.val(val);}
if(itemNo.substr(2)=="00"){selectedItem.find("li[@no^="+itemNo.substr(0,2)+"]").not("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());var tmp=val.split(",");var valArr=new Array();for(var i=0;i<tmp.length;i++){if(tmp[i]==""){continue;}
if(tmp[i].substr(0,2)==itemNo.substr(0,2)){if(tmp[i]!=itemNo){continue;}}
valArr.push(tmp[i]);}
selectValue.val(valArr.join(","));}}else{selectedItem.find("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());val=val.replace(itemNo,"");val=val.replace(/,+/g,",");if(","==val)
val="";selectValue.val(val);}
this.displayTips();if(self.maxMun==1){if(selectedItem.find("li").length==1){self.submitItem();}}
if(itemNo.substr(2)=="00"){var selectedItem=this.getContainer().find(".tipsmaintop ul");var smallItem=selectedItem.find("li").eq(0);if(smallItem.length!=0){if(smallItem.attr("no").substr(0,2)==itemNo.substr(0,2)){var smallItems=selectedItem.find("li");smallItems.find("input[@name=check_value]").val(isChecked).attr("disabled",isChecked);if(isChecked){smallItems.unbind("click");}else{smallItems.click(function(){var checkbox=jQuery(this).find("input[@name=check_value]");checkbox.attr(!checkbox.val());self.clickItem(checkbox.parent().parent().attr("no"));});}}}}},displayTips:function(){if(this.getContainer().find(".tipsmaintop li").length>0){this.getContainer().find(".tipsmaintop p").hide();}else{this.getContainer().find(".tipsmaintop p").show();}},remove:function(){this.getContainer().remove();this.container=null;this.getOverlay().remove();this.overlay=null;},hasChild:function(itemNo){if(itemNo.substr(2)!=00){return false;}
var oItem;var key=itemNo.substr(0,2);for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0].substr(0,2)!=key){continue;}
if(itemNo!=oItem[0]){return true;}}
return false;},getFunText:function(itemNo){var text="";for(var i=0;i<this.data.length;i++){var key=itemNo.substr(0,2);if(this.data[i][0].substr(0,2)==key){if(this.data[i][0].substr(2)=="00"){text+=this.data[i][1];if(itemNo==this.data[i][0]){return text;}
text+="-";}else{if(this.data[i][0]==itemNo){text+=this.data[i][1];return text;}}}}},windowSize:function(){var wWidth=0,wHeight=0;if(typeof(top.window.innerWidth)=='number'){wWidth=top.window.innerWidth;wHeight=top.window.innerHeight;}else if(top.document.documentElement&&(top.document.documentElement.clientWidth||top.document.documentElement.clientHeight)){wWidth=top.document.documentElement.clientWidth;wHeight=top.document.documentElement.clientHeight;}else if(top.document.body&&(top.document.body.clientWidth||top.document.body.clientHeight)){wWidth=top.document.body.clientWidth;wHeight=top.document.body.clientHeight;}
return[wWidth,wHeight];},getScrollTop:function(){return top.document.body.scrollTop>0?top.document.body.scrollTop:top.document.documentElement.scrollTop;},getItem:function(name){var _item=jQuery("#"+name);if(_item.length==0){_item=jQuery("[@name="+name+"]").eq(0);}
return _item;}};AreaExpectPopSelect.prototype={form:null,show:null,value:null,maxMun:null,title:null,tips:null,height:null,width:null,data:null,sender:null,fullText:null,defaultText:null,showByItem:null,topJQuery:top.jQuery,container:null,containerId:"pop_container",timmer:null,overlayId:"pop_overlay",overlay:null,initialize:function(args){var self=this;if("undefined"==typeof(args.show)||"undefined"==typeof(args.value)||"undefined"==typeof(args.data)||"undefined"==typeof(args.sender)){alert("@error in initialize, check args");}
this.form=args.form||"form1";this.show=args.show;this.value=args.value;this.maxMun=args.maxMun||5;this.data=args.data;this.title=args.title||"";this.tips=args.tips||"";this.sender=args.sender;this.width=args.width||400;this.defaultText=args.defaultText||"";this.height=args.height||510;if(typeof(args.fullText)=="undefined"){this.fullText=true;}else{this.fullText=args.fullText;}
if(typeof(args.showByItem)=="undefined"){this.showByItem=false;}else{this.showByItem=args.showByItem;}
if(typeof(args.chosen)!="undefined"){this.submitItemToItem(args.chosen);}
var sender=this.getItem(this.sender);sender.click(function(){self.display();});},getContainer:function(){if(null==this.container){if(this.topJQuery("#"+this.containerId).length==0){this.topJQuery("body").append("<div id=\""+this.containerId
+"\"></div>");}
this.container=this.topJQuery("#"+this.containerId);}
this.container.find(".boxwrap").css({width:this.width});return this.container;},getOverlay:function(){if(null==this.overlay){if(this.topJQuery("#"+this.overlayId).length==0){this.topJQuery("body").append("<iframe id=\""+this.overlayId
+"\" class=\"pop_overlayBG\"></iframe>");}
this.overlay=this.topJQuery("#"+this.overlayId);if(typeof(top.window.innerWidth)!='number'){this.overlay.css("height","0");this.overlay.css({"position":"absolute","height":this.topJQuery("body").get(0).scrollHeight});}}
return this.overlay;},display:function(){this._dispaly();this.getContainer().show();this.getOverlay().show();this.bindBigBox();},bindBigBox:function(){var self=this;var value=jQuery("form[@name="+this.form+"] input[@name="
+this.value+"]");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var sel=jQuery.trim(value.val());var selArr=sel==""?[]:sel.split(",");var key;var value;var oItem;var oItems=Array();for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];if("00"==key.substr(2)){oItems.push(oItem);}}
var htmlLine_city=new Array();var htmlLine_province=new Array();var className="";for(var i=0;i<oItems.length;i++){oItem=oItems[i];className=self.hasChild(oItem[0])?"":'class="noico"';if(self.isCity(oItem[0])){htmlLine_city.push('<li no='+oItem[0]+'><a href="'+aHref
+'" '+className+'><input type="checkbox" /> '
+oItem[1]+' </a></li>');continue;}else{htmlLine_province.push('<li no='
+oItem[0]
+'><a href="'
+aHref
+'" '
+className
+'>'
+oItem[1]
+'<input name="check_value" type="hidden" value="false"/></a></li>');continue;}}
var bigBox=this.getContainer().find(".boxOptions");bigBox.html("<div>直辖市</div><ul>"+htmlLine_city.join("\n")
+"</ul><div>所有省份</div><ul>"+htmlLine_province.join("\n")
+"</ul>");bigBox.find("li").unbind("mouseover").mouseover(function(event){if(self.timmer!=null){clearTimeout(self.timmer);}
var no=jQuery(this).attr("no");self.timmer=setTimeout(function(){self.overBigItem(no,event);},300);}).unbind("mouseout").mouseout(function(){if(self.timmer!=null){clearTimeout(self.timmer);}
self.timmer=setTimeout(function(){self.getContainer().find(".areaExpectBoxiiOptions").hide();},100);}).unbind("click").click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().parent().attr("no"));}).find("input[@type=checkbox]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});this.getContainer().find("[@name=select_value]").val(sel);for(var i=0;i<selArr.length;i++){if(selArr[i]==""){continue;}
this.getContainer().find("li[@no="+selArr[i]+"]").find("input[@type=checkbox]").attr("checked",true);var text=this.getFunText(selArr[i]);this.getContainer().find(".tipsmaintop1 ul").append('<li no='
+selArr[i]+'><a href="'+aHref+'" title="点击删除">'
+text+'</a></li>').find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".boxOptions , .areaExpectBoxiiOptions").find("li[@no="+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@type=checkbox]").attr("checked",false);}
self.clickItem(srcNo);});}
this.displayTips();},isCity:function(item){var city=new Array("1100","1000","1200","1300","4100","4200","4300","4400","4500");for(var i=0;i<city.length;i++){if(city[i]==item){return true;}}
return false;},pointerX:function(event){return event.pageX||(event.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft));},pointerY:function(event){return event.pageY||(event.clientY+(document.documentElement.scrollTop||document.body.scrollTop));},overBigItem:function(itemNo,event){var self=this;var key=itemNo.substr(0,2);var oItems=new Array();var htmlLine=new Array();var smallBox=this.getContainer().find(".areaExpectBoxiiOptions");if(this.getContainer().find(".boxOptions li[@no="+itemNo+"] a").attr("class")=="noico"){smallBox.hide();return;}
var oItem;for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0].substr(0,2)==key){if(oItem[0]==itemNo){htmlLine.push('<li no="'+oItem[0]
+'" style="width:100%;font-weight:bold"><a href="'
+aHref+'" title="'+oItem[1]
+'"><input type="checkbox" /> '
+oItem[1].substring(0,8)+' </li>');continue;}
oItems.push(oItem);}}
for(var i=0;i<oItems.length;i++){oItem=oItems[i];htmlLine.push('<li no='+oItem[0]+'><a href="'+aHref
+'" title="'+oItem[1]+'"><input type="checkbox" /> '
+oItem[1].substring(0,8)+' </a></li>');}
smallBox.html("<ul>"+htmlLine.join("\n")+"</ul>");smallBox.find("li").mouseout(function(){if(self.timmer!=null){clearTimeout(self.timmer);}
self.timmer=setTimeout(function(){smallBox.hide();},100);}).unbind("mouseover").mouseover(function(event){if(self.timmer!=null){clearTimeout(self.timmer);}}).unbind("click").click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().parent().attr("no"));}).find("input[@type=checkbox]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});var bigBox=this.getContainer().find(".multiBoxOptions");var bChecked=bigBox.find("li[@no="+itemNo
+"] input[@type=checkbox]").attr("checked");if(bChecked){smallBox.find("li").unbind("click").end().find("input[@type=checkbox]").unbind("click").attr("checked",true).attr("disabled",true);}else{var selVal=this.getContainer().find("[@name=select_value]").val();var selArr=selVal.split(",");for(var i=0;i<selArr.length;i++){smallBox.find("li[@no="+selArr[i]+"] input[@type=checkbox]").attr("checked",true);}}
var sender=event.currentTarget||event.srcElement;sender=jQuery(sender);try{var wSize=this.windowSize();var top=sender.offset().top
var left=null;if(sender.offset().left
-this.getContainer().find(".boxOptions").offset().left<200){left=sender.offset().left+sender.width();}else{left=sender.offset().left-smallBox.width();}
if(top+smallBox.height()>(wSize[1]+self.getScrollTop())){top=wSize[1]+self.getScrollTop()-smallBox.height();}
smallBox.css("top",top).css("left",left).show();}catch(e){alert("调整二级菜单位置"+e);}},_dispaly:function(){var self=this;var html="";html+='<div class="boxwrap">';html+=' <h3>';html+='  <span><a href="'+aHref+'" id="close" title="关闭"></a>';html+='  </span>'+this.title;html+=' </h3>';html+=' <div class="boxinwrap">';html+='  <!--弹出层开始 -->';html+='  <div class="box">';html+='   <!--顶部开始 -->';html+='   <div class="boxheader">';html+='    <!--提示开始 -->';html+='    <div class="tips">';html+='     <span>';html+='      <input type="button" name="sub" value="确定" />';html+='      <input name="select_value" type="hidden" />';html+='      <input type="button" name="cls" value="清空" />';html+='     </span>提示：';html+='    </div>';html+='    <!--提示开始 -->';html+='    <!--结果开始 -->';html+='    <div class="tipsmaintop1">';html+='     <p>';html+='      符号＂';html+='      <img src="'+basePath
+'images/ico.gif" align="middle" />';html+='      ＂下的含具体选项';html+='      <br />';html+='      您最多可以选择'+self.maxMun+'个选项';html+='     </p>';html+='     <ul></ul>';html+='    </div>';html+='    <!--结果结束 -->';html+='   </div>';html+='   <!--顶部结束 -->';html+='   <!--选项开始 -->';html+='   <div class="boxOptions">';html+='   </div>';html+='   <!--选项结束 -->';html+='  </div>';html+='  <!--弹出层结束 -->';html+=' </div>';html+='</div>';html+='<!--二级选项开始 -->';html+='<div class="areaExpectBoxiiOptions" style="display:none">';html+='</div>';html+='<!--二级选项结束 -->';this.getContainer().html(html);var wSize=this.windowSize();var left=wSize[0]/2-this.getContainer().find(".boxwrap").width()/2;this.getContainer().find(".boxwrap").css("left",left);this.getContainer().find(".boxwrap").css("top",self.getScrollTop()+60);this.getContainer().find("[@name=sub]").click(function(){self.submitItem();});this.getContainer().find("[@name=cls]").click(function(){self.clearItem();});this.getContainer().find("#close").click(function(){self.remove();});},submitItem:function(){if(this.showByItem){this.submitItemToItem();}else{this.submitItemToInput();}},submitItemToInput:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var showText="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
showText+=text+" ";}}
if(showText==""){showText+=this.defaultText;}
show.val(jQuery.trim(showText));this.remove();},submitItemToItem:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var html="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
html+='<div><span>'+text
+'</span><a title="点击删除" href="javascript://" no="'
+valArr[i]+'">X</a></div>';}}
if(html==""){html+='<div><span>'+this.defaultText+'</span></div>';}
show.html(html);show.find("a").hover(function(){self.itemMoveOver(this);},function(){self.itemMoveOut(this);}).click(function(){self.itemDelete(this);});this.remove();},itemMoveOver:function(sender){sender=jQuery(sender);var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");show.find("div").removeClass();sender.parent().addClass("pop_widhtDIVBG");},itemMoveOut:function(sender){sender=jQuery(sender);sender.parent().removeClass();},itemDelete:function(sender){sender=jQuery(sender);var no=sender.attr("no");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var val=value.val();val=val.replace(no,"");val=val.replace(/\,+/g,",");if(val.substr(val.length-1)==","){val=val.substr(0,val.length-1);}
value.val(val);sender.parent().remove();var show=form.find("[@name="+this.show+"]");if(show.html()==""){show.html("<div>&nbsp;</div>")}},clearItem:function(){var self=this;var selectedItem=this.getContainer().find(".tipsmaintop1");var selectValue=this.getContainer().find("[@name=select_value]");selectValue.val("");selectedItem.find("li").remove();this.getContainer().find(".boxOptions input[@type=checkbox]").attr("checked",false).attr("disabled",false);this.getContainer().find(".areaExpectBoxiiOptions input[@type=checkbox]").attr("checked",false).attr("disabled",false);this.getContainer().find(".tipsmaintop1 p").show();},clickItem:function(itemNo){var self=this;var sender=this.getContainer().find(".boxOptions , .areaExpectBoxiiOptions").find("li[@no="
+itemNo+"]");var checkbox=sender.find("input[@type=checkbox]");var isChecked=checkbox.length>0?checkbox.attr("checked"):false;var selectValue=this.getContainer().find("[@name=select_value]");var selectedItem=this.getContainer().find(".tipsmaintop1 ul");if(isChecked&&selectedItem.find("li").length>=this.maxMun){alert("对不起，您只能选择"+this.maxMun+"项");checkbox.attr("checked",false);return;}
if(isChecked){if(selectedItem.find("li[@no="+itemNo+"]").length==0){var text=this.getFunText(itemNo);selectedItem.append('<li no='+itemNo+'><a href="'+aHref
+'" title="点击删除">'+text+'</a></li>');selectedItem.find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".boxOptions , .areaExpectBoxiiOptions").find("li[@no="+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@type=checkbox]").attr("checked",false);}
self.clickItem(srcNo);});}
if(selectValue.val().indexOf(itemNo)==-1){var val=selectValue.val();val+=val==""?"":",";val+=itemNo;selectValue.val(val);}
if(itemNo.substr(2)=="00"){selectedItem.find("li[@no^="+itemNo.substr(0,2)+"]").not("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());var tmp=val.split(",");var valArr=new Array();for(var i=0;i<tmp.length;i++){if(tmp[i]==""){continue;}
if(tmp[i].substr(0,2)==itemNo.substr(0,2)){if(tmp[i]!=itemNo){continue;}}
valArr.push(tmp[i]);}
selectValue.val(valArr.join(","));}}else{selectedItem.find("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());val=val.replace(itemNo,"");val=val.replace(/,+/g,",");if(","==val)
val="";selectValue.val(val);}
this.displayTips();if(self.maxMun==1){if(selectedItem.find("li").length==1){self.submitItem();}}
if(itemNo.substr(2)=="00"){var smallBox=this.getContainer().find(".areaExpectBoxiiOptions");var smallItem=smallBox.find("li").eq(0);if(smallItem.length!=0){if(smallItem.attr("no").substr(0,2)==itemNo.substr(0,2)){var smallItems=smallBox.find("li");smallItems.find("input[@type=checkbox]").attr("checked",isChecked).attr("disabled",isChecked);if(isChecked){smallItems.unbind("click");}else{smallItems.click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().parent().attr("no"));});}}}}},displayTips:function(){if(this.getContainer().find(".tipsmaintop1 li").length>0){this.getContainer().find(".tipsmaintop1 p").hide();}else{this.getContainer().find(".tipsmaintop1 p").show();}},remove:function(){this.getContainer().remove();this.container=null;this.getOverlay().remove();this.overlay=null;},hasChild:function(itemNo){if(itemNo.substr(2)!=00){return false;}
var oItem;var key=itemNo.substr(0,2);for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0].substr(0,2)!=key){continue;}
if(itemNo!=oItem[0]){return true;}}
return false;},getFunText:function(itemNo){var text="";for(var i=0;i<this.data.length;i++){if(this.data[i][0]==itemNo){text+=this.data[i][1];return text;}}},windowSize:function(){var wWidth=0,wHeight=0;if(typeof(top.window.innerWidth)=='number'){wWidth=top.window.innerWidth;wHeight=top.window.innerHeight;}else if(top.document.documentElement&&(top.document.documentElement.clientWidth||top.document.documentElement.clientHeight)){wWidth=top.document.documentElement.clientWidth;wHeight=top.document.documentElement.clientHeight;}else if(top.document.body&&(top.document.body.clientWidth||top.document.body.clientHeight)){wWidth=top.document.body.clientWidth;wHeight=top.document.body.clientHeight;}
return[wWidth,wHeight];},getScrollTop:function(){return top.document.body.scrollTop>0?top.document.body.scrollTop:top.document.documentElement.scrollTop;},getItem:function(name){var _item=jQuery("#"+name);if(_item.length==0){_item=jQuery("[@name="+name+"]").eq(0);}
return _item;}};JobTypePopSelect.prototype={form:null,show:null,value:null,maxMun:null,title:null,tips:null,height:null,width:null,data:null,sender:null,fullText:null,defaultText:null,showByItem:null,topJQuery:top.jQuery,container:null,containerId:"pop_container",overlayId:"pop_overlay",overlay:null,initialize:function(args){var self=this;if("undefined"==typeof(args.show)||"undefined"==typeof(args.value)||"undefined"==typeof(args.data)||"undefined"==typeof(args.sender)){alert("@error in initialize, check args");}
this.form=args.form||"form1";this.show=args.show;this.value=args.value;this.maxMun=args.maxMun||5;this.data=args.data;this.title=args.title||"";this.tips=args.tips||"";this.sender=args.sender;this.width=args.width||400;this.defaultText=args.defaultText||"";this.height=args.height||510;if(typeof(args.fullText)=="undefined"){this.fullText=true;}else{this.fullText=args.fullText;}
if(typeof(args.showByItem)=="undefined"){this.showByItem=false;}else{this.showByItem=args.showByItem;}
if(typeof(args.chosen)!="undefined"){this.submitItemToItem(args.chosen);}
var sender=this.getItem(this.sender);sender.click(function(){self.display();});},getContainer:function(){if(null==this.container){if(this.topJQuery("#"+this.containerId).length==0){this.topJQuery("body").append("<div id=\""+this.containerId
+"\"></div>");}
this.container=this.topJQuery("#"+this.containerId);}
this.container.find(".boxwrap").css({width:this.width});return this.container;},getOverlay:function(){if(null==this.overlay){if(this.topJQuery("#"+this.overlayId).length==0){this.topJQuery("body").append("<iframe id=\""+this.overlayId
+"\" class=\"pop_overlayBG\"></iframe>");}
this.overlay=this.topJQuery("#"+this.overlayId);if(typeof(top.window.innerWidth)!='number'){this.overlay.css("height","0");this.overlay.css({"position":"absolute","height":this.topJQuery("body").get(0).scrollHeight});}}
return this.overlay;},display:function(){this._dispaly();this.getContainer().show();this.getOverlay().show();this.bindBigBox();},bindBigBox:function(){var self=this;var value=jQuery("form[@name="+this.form+"] input[@name="
+this.value+"]");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var sel=jQuery.trim(value.val());var selArr=sel==""?[]:sel.split(",");var key;var value;var oItem;var oItems=Array();for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];if("00"==key.substr(2)){oItems.push(oItem);}}
var htmlLine=new Array();var className="";for(var i=0;i<oItems.length;i++){oItem=oItems[i];className="class='noico'";htmlLine.push('<li no='+oItem[0]+'><a href="'+aHref+'" '
+className+' title='+oItem[1]+'>'+oItem[1]
+'<input name="check_value" type="hidden"/></a></li>');}
var bigBox=this.getContainer().find(".singleBoxOptions1");bigBox.html('<div>所有职位类别</div><ul>'+htmlLine.join("\n")+'</ul>');bigBox.find("li").unbind("click").click(function(event){var no=jQuery(this).attr("no");self.overBigItem(no,event);event.stopPropagation();});this.getContainer().find("[@name=select_value]").val(sel);for(var i=0;i<selArr.length;i++){if(selArr[i]==""){continue;}
this.getContainer().find("li[@no="+selArr[i]+"]").find("input[@name=check_value]").val("true");var text=this.getFunText(selArr[i]);this.getContainer().find(".tipsmaintop ul").append('<li no='
+selArr[i]+'><a href="'+aHref+'" title="点击删除">'
+text+'</a></li>').find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".singleBoxOptions1").find("li[@no="
+srcNo+"]");if(srcSendr.length>=0){srcSendr.find("input[@name=check_value]").val("false");}
self.clickItem(srcNo);});}
this.displayTips();},bindBigBox1:function(){var self=this;var key;var value;var oItem;var oItems=Array();for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];if("00"==key.substr(2)){oItems.push(oItem);}}
var htmlLine=new Array();var className="";for(var i=0;i<oItems.length;i++){oItem=oItems[i];className="class='noico'";htmlLine.push('<li no='+oItem[0]+'><a href="'+aHref+'" '
+className+' title='+oItem[1]+'>'+oItem[1]
+'<input name="check_value" type="hidden"/></a></li>');}
var bigBox=this.getContainer().find(".singleBoxOptions1");bigBox.html('<div>所有职位类别</div><ul>'+htmlLine.join("\n")+'</ul>');bigBox.find("li").unbind("click").click(function(event){var no=jQuery(this).attr("no");self.overBigItem(no,event);event.stopPropagation();});this.displayTips();},overBigItem:function(itemNo,event){var itemName;var self=this;var key=itemNo.substr(0,2);var oItems=new Array();var htmlLine=new Array();var selectedItem=this.getContainer().find(".singleBoxOptions1");var oItem;for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0]==itemNo){itemName=oItem[1];}
if(oItem[0].substr(0,2)==key){if(oItem[0]==itemNo){continue;}
oItems.push(oItem);}}
var className="class=noico";for(var i=0;i<oItems.length;i++){oItem=oItems[i];htmlLine.push('<li no='+oItem[0]+'><a href="'+aHref+'"'
+className+' title='+oItem[1]+'>'+oItem[1]
+'<input name="check_value" type="hidden"/></a></li>');}
selectedItem.html('<div>'+itemName+'&nbsp;&nbsp;&nbsp;<a href="'
+aHref+'">'+'[返回所有职位类别]</a></div><ul>'
+htmlLine.join('\n')+'</ul>');selectedItem.find("div a").unbind("click").click(function(){self.bindBigBox1();});selectedItem.find("li").unbind("click").click(function(){var check=jQuery(this).find("input[@name=check_value]");if(check.val()==""){check.val(!check.val());}
self.clickItem(check.parent().parent().attr("no"));}).find("input[@name=check_value]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().parent().attr("no"));event.stopPropagation();});},_dispaly:function(){var self=this;var html="";html+='<div class="boxwrap">';html+=' <h3>';html+='  <span><a href="'+aHref+'" id="close" title="关闭"></a>';html+='  </span>'+this.title;html+=' </h3>';html+=' <div class="boxinwrap">';html+='  <!--弹出层开始 -->';html+='  <div class="box">';html+='   <!--顶部开始 -->';html+='   <div class="boxheader">';html+='    <!--提示开始 -->';html+='    <div class="tips">';html+='     <span>';html+='      <input type="button" name="sub" value="确定" />';html+='      <input name="select_value" type="hidden" />';html+='      <input type="button" name="cls" value="清空" />';html+='     </span>提示：';html+='    </div>';html+='    <!--提示开始 -->';html+='    <!--结果开始 -->';html+='    <div class="tipsmaintop">';html+='     <p>';html+='      您最多可以选择'+self.maxMun+'个选项';html+='     </p>';html+='     <ul></ul>';html+='    </div>';html+='    <!--结果结束 -->';html+='   </div>';html+='   <!--顶部结束 -->';html+='   <!--选项开始 -->';html+='   <div class="singleBoxOptions1">';html+='   </div>';html+='   <!--选项结束 -->';html+='  </div>';html+='  <!--弹出层结束 -->';html+=' </div>';html+='</div>';html+='<!--二级选项结束 -->';this.getContainer().html(html);var wSize=this.windowSize();var left=wSize[0]/2-this.getContainer().find(".boxwrap").width()/2;this.getContainer().find(".boxwrap").css("left",left);this.getContainer().find(".boxwrap").css("top",self.getScrollTop()+60);this.getContainer().find("[@name=sub]").click(function(){self.submitItem();});this.getContainer().find("[@name=cls]").click(function(){self.clearItem();});this.getContainer().find("#close").click(function(){self.remove();});},submitItem:function(){if(this.showByItem){this.submitItemToItem();}else{this.submitItemToInput();}},submitItemToInput:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var showText="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
showText+=text+" ";}}
if(showText==""){showText+=this.defaultText;}
show.val(jQuery.trim(showText));this.remove();},submitItemToItem:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);var html="";var text;if(null!=val){var valArr=val.split(",");for(var i=0;i<valArr.length;i++){text=self.getFunText(valArr[i]);if(!text){continue;}
if(!self.fullText){var tmp=text.split("-");text=tmp[tmp.length-1];}
html+='<div><span>'+text
+'</span><a title="点击删除" href="javascript://" no="'
+valArr[i]+'">X</a></div>';}}
if(html==""){html+='<div><span>'+this.defaultText+'</span></div>';}
show.html(html);show.find("a").hover(function(){self.itemMoveOver(this);},function(){self.itemMoveOut(this);}).click(function(){self.itemDelete(this);});this.remove();},itemMoveOver:function(sender){sender=jQuery(sender);var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");show.find("div").removeClass();sender.parent().addClass("pop_widhtDIVBG");},itemMoveOut:function(sender){sender=jQuery(sender);sender.parent().removeClass();},itemDelete:function(sender){sender=jQuery(sender);var no=sender.attr("no");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var val=value.val();val=val.replace(no,"");val=val.replace(/\,+/g,",");if(val.substr(val.length-1)==","){val=val.substr(0,val.length-1);}
value.val(val);sender.parent().remove();var show=form.find("[@name="+this.show+"]");if(show.html()==""){show.html("<div>&nbsp;</div>")}},clearItem:function(){var self=this;var selectedItem=this.getContainer().find(".tipsmaintop");var selectValue=this.getContainer().find("[@name=select_value]");selectValue.val("");selectedItem.find("li").remove();this.getContainer().find(".singleBoxOptions1 input[@name=check_value]").val("false").attr("disabled",false);this.getContainer().find(".tipsmaintop p").show();},clickItem:function(itemNo){var self=this;var sender=this.getContainer().find(".singleBoxOptions1").find("li[@no="+itemNo+"]");var checkbox=sender.find("input[@name=check_value]");var isChecked=checkbox.length>0?checkbox.val():false;var selectValue=this.getContainer().find("[@name=select_value]");var selectedItem=this.getContainer().find(".tipsmaintop ul");if(isChecked&&selectedItem.find("li").length>=this.maxMun){alert("对不起，您只能选择"+this.maxMun+"项");checkbox.val("false");return;}
if(isChecked=="true"){if(selectedItem.find("li[@no="+itemNo+"]").length==0){var text=this.getFunText(itemNo);selectedItem.append('<li no='+itemNo+'><a href="'+aHref
+'" title="点击删除">'+text+'</a></li>');selectedItem.find("li").unbind("click").click(function(){var srcNo=jQuery(this).attr("no");var srcSendr=self.getContainer().find(".singleBoxOptions1").find("li[@no="+srcNo
+"]");if(srcSendr.length>=0){srcSendr.find("input[@name=check_value]").val("");}
self.clickItem(srcNo);});}
if(selectValue.val().indexOf(itemNo)==-1){var val=selectValue.val();val+=val==""?"":",";val+=itemNo;selectValue.val(val);}}else{selectedItem.find("li[@no="+itemNo+"]").remove();var val=jQuery.trim(selectValue.val());val=val.replace(itemNo,"");val=val.replace(/,+/g,",");if(","==val)
val="";selectValue.val(val);}
this.displayTips();if(self.maxMun==1){if(selectedItem.find("li").length==1){self.submitItem();}}},displayTips:function(){if(this.getContainer().find(".tipsmaintop li").length>0){this.getContainer().find(".tipsmaintop p").hide();}else{this.getContainer().find(".tipsmaintop p").show();}},remove:function(){this.getContainer().remove();this.container=null;this.getOverlay().remove();this.overlay=null;},hasChild:function(itemNo){if(itemNo.substr(2)!=00){return false;}
var oItem;var key=itemNo.substr(0,2);for(var i=0;i<this.data.length;i++){oItem=this.data[i];if(oItem[0].substr(0,2)!=key){continue;}
if(itemNo!=oItem[0]){return true;}}
return false;},getFunText:function(itemNo){var text="";for(var i=0;i<this.data.length;i++){var key=itemNo.substr(0,2);if(this.data[i][0].substr(0,2)==key){if(this.data[i][0].substr(2)=="00"){text+=this.data[i][1];if(itemNo==this.data[i][0]){return text;}
text+="-";}else{if(this.data[i][0]==itemNo){text+=this.data[i][1];return text;}}}}},windowSize:function(){var wWidth=0,wHeight=0;if(typeof(top.window.innerWidth)=='number'){wWidth=top.window.innerWidth;wHeight=top.window.innerHeight;}else if(top.document.documentElement&&(top.document.documentElement.clientWidth||top.document.documentElement.clientHeight)){wWidth=top.document.documentElement.clientWidth;wHeight=top.document.documentElement.clientHeight;}else if(top.document.body&&(top.document.body.clientWidth||top.document.body.clientHeight)){wWidth=top.document.body.clientWidth;wHeight=top.document.body.clientHeight;}
return[wWidth,wHeight];},getScrollTop:function(){return top.document.body.scrollTop>0?top.document.body.scrollTop:top.document.documentElement.scrollTop;},getItem:function(name){var _item=jQuery("#"+name);if(_item.length==0){_item=jQuery("[@name="+name+"]").eq(0);}
return _item;}};PopCon.prototype={form:null,show:null,value:null,maxMun:null,title:null,tips:null,height:null,width:null,data:null,sender:null,fullText:null,defaultText:null,showByItem:null,topJQuery:top.jQuery,container:null,containerId:"pop_container",timmer:null,overlayId:"pop_overlay",overlay:null,top:null,initialize:function(args){var self=this;if("undefined"==typeof(args.show)||"undefined"==typeof(args.value)||"undefined"==typeof(args.data)||"undefined"==typeof(args.sender)){alert("@error in initialize, check args");}
this.form=args.form||"form1";this.show=args.show;this.value=args.value;this.maxMun=args.maxMun||5;this.data=args.data;this.title=args.title||"";this.tips=args.tips||"";this.sender=args.sender;this.width=args.width||400;this.defaultText=args.defaultText||"";this.height=args.height||510;if(typeof(args.fullText)=="undefined"){this.fullText=true;}else{this.fullText=args.fullText;}
if(typeof(args.showByItem)=="undefined"){this.showByItem=false;}else{this.showByItem=args.showByItem;}
var sender=this.getItem(this.sender);sender.click(function(){self.display();this.top=top.document.body.scrollTop>0?top.document.body.scrollTop:top.document.documentElement.scrollTop;});},getContainer:function(){if(null==this.container){if(jQuery("#"+this.containerId).length==0){jQuery("body").append("<div id=\""+this.containerId
+"\"></div>");}
this.container=jQuery("#"+this.containerId);}
this.container.find(".boxwrap").css({width:this.width});return this.container;},getOverlay:function(){if(null==this.overlay){if(jQuery("#"+this.overlayId).length==0){jQuery("body").append("<iframe id=\""+this.overlayId
+"\" class=\"pop_overlayBG\"></iframe>");}
this.overlay=jQuery("#"+this.overlayId);if(typeof(top.window.innerWidth)!='number'){this.overlay.css("height","0");this.overlay.css({"position":"absolute","height":jQuery("body").get(0).scrollHeight});}}
return this.overlay;},display:function(){this._dispaly();this.getContainer().show();this.getOverlay().show();this.bindBigBox();},bindBigBox:function(){var self=this;var value=jQuery("form[@name="+this.form+"] input[@name="
+this.value+"]");var form=this.getItem(this.form);var value=form.find("[@name="+this.value+"]");var sel=jQuery.trim(value.val());var selArr=sel==""?[]:sel.split(",");var key;var value;var oItem;var oItems=Array();for(var i=0;i<this.data.length;i++){oItem=this.data[i];key=oItem[0];oItems.push(oItem);}
var htmlLine=new Array();for(var i=0;i<oItems.length;i++){oItem=oItems[i];htmlLine.push('<li no='+oItem[0]+'><input type="checkbox"/> '
+oItem[1]+' </li>');}
var bigBox=this.getContainer().find(".multiBoxOptions");bigBox.html("<ul>"+htmlLine.join("\n")+"</ul>");jQuery(this).find("input[@name=select_value]").val(sel);bigBox.find("li").unbind("click").click(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",!checkbox.attr("checked"));self.clickItem(checkbox.parent().attr("no"));}).find("input[@type=checkbox]").unbind("click").click(function(event){self.clickItem(jQuery(this).parent().attr("no"));event.stopPropagation();});this.getContainer().find("[@name=select_value]").val(sel);for(var i=0;i<selArr.length;i++){if(selArr[i]==""){continue;}
this.getContainer().find("li[@no="+selArr[i]+"]").find("input[@type=checkbox]").attr("checked",true);}},_dispaly:function(){var self=this;var html="";html+='<div class="boxwrap">';html+=' <h3>';html+='  <a id="all_select" style="float:left;" href="'+aHref
+'">【全选】</a>';html+='       <a id="all_clear" style="float:left;" href="'+aHref
+'">【取消】</a>';html+='  <a id="close" style="float:right;" href="'+aHref
+'">确定</a>';html+=' </h3>';html+=' <div class="boxinwrap">';html+='  <!--弹出层开始 -->';html+='  <div class="box">';html+='   <input name="select_value" type="hidden" />';html+='   <!--选项开始 -->';html+='   <div class="multiBoxOptions">';html+='   </div>';html+='   <!--选项结束 -->';html+='  </div>';html+='  <!--弹出层结束 -->';html+=' </div>';html+='</div>';this.getContainer().html(html);var wSize=this.windowSize();var left=wSize[0]/2-this.getContainer().find(".boxwrap").width()/2;this.getContainer().find(".boxwrap").css("left",left+135);this.getContainer().find(".boxwrap").css("top",self.getScrollTop()+250);this.getContainer().find("#close").click(function(){self.submitItemToInput();self.remove();});this.getContainer().find("#all_select").click(function(){var bigBox=self.getContainer().find(".multiBoxOptions");bigBox.find("li").each(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",true);});var selectValue=self.getContainer().find("[@name=select_value]");var value="1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300";selectValue.val(value);});this.getContainer().find("#all_clear").click(function(){var bigBox=self.getContainer().find(".multiBoxOptions");bigBox.find("li").each(function(){var checkbox=jQuery(this).find("input[@type=checkbox]");checkbox.attr("checked",false);});var selectValue=self.getContainer().find("[@name=select_value]");selectValue.val("");});},remove:function(){this.getContainer().remove();this.container=null;this.getOverlay().remove();this.overlay=null;},clickItem:function(itemNo){var self=this;var sender=this.getContainer().find(".multiBoxOptions").find("li[@no="+itemNo+"]");var checkbox=sender.find("input[@type=checkbox]");var selectValue=this.getContainer().find("[@name=select_value]");if(selectValue.val().indexOf(itemNo)==-1){var val=selectValue.val();val+=val==""?"":",";val+=itemNo;selectValue.val(val);}else{var val=jQuery.trim(selectValue.val());val=val.replace(itemNo,"");val=val.replace(/\,+/g,",");if(","==val)
val="";selectValue.val(val);}},submitItemToInput:function(val){var self=this;var form=this.getItem(this.form);var show=form.find("[@name="+this.show+"]");var value=form.find("[@name="+this.value+"]");if(typeof(val)=="undefined"){val=this.getContainer().find("[@name=select_value]").val();}
val=val.replace(/\,+/g,",");val=jQuery.trim(val);value.val(val);jQuery(".company_spanright a").each(function(i){jQuery(this).click(function(){var itemNo=jQuery(this).attr("no");var val=jQuery("[@name=baohan]").val();val=val.replace(itemNo,"");val=val.replace(/\,+/g,",");jQuery("[@name=baohan]").val(val);jQuery(this).parent().parent().remove();});jQuery(this).mousemove(function(){jQuery(this).parent().parent().css("backgroundColor","#ccc");});jQuery(this).mouseout(function(){jQuery(this).parent().parent().css("backgroundColor","#fff");});});this.remove();},getFunText:function(itemNo){var text="";for(var i=0;i<this.data.length;i++){var key=itemNo.substr(0,2);if(this.data[i][0].substr(0,2)==key){if(this.data[i][0].substr(2)=="00"){text+=this.data[i][1];if(itemNo==this.data[i][0]){return text;}
text+="-";}else{if(this.data[i][0]==itemNo){text+=this.data[i][1];return text;}}}}},windowSize:function(){var wWidth=0,wHeight=0;if(typeof(top.window.innerWidth)=='number'){wWidth=top.window.innerWidth;wHeight=top.window.innerHeight;}else if(top.document.documentElement&&(top.document.documentElement.clientWidth||top.document.documentElement.clientHeight)){wWidth=top.document.documentElement.clientWidth;wHeight=top.document.documentElement.clientHeight;}else if(top.document.body&&(top.document.body.clientWidth||top.document.body.clientHeight)){wWidth=top.document.body.clientWidth;wHeight=top.document.body.clientHeight;}
return[wWidth,wHeight];},getScrollTop:function(){return top.document.body.scrollTop>0?top.document.body.scrollTop:top.document.documentElement.scrollTop;},getItem:function(name){var _item=jQuery("#"+name);if(_item.length==0){_item=jQuery("[@name="+name+"]").eq(0);}
return _item;}};
/*
     FILE ARCHIVED ON 04:37:34 Mar 15, 2015 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 12:53:59 May 14, 2020.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  RedisCDXSource: 8.155
  LoadShardBlock: 276.89 (3)
  esindex: 0.026
  captures_list: 319.928
  CDXLines.iter: 27.882 (3)
  PetaboxLoader3.resolve: 1442.187 (3)
  exclusion.robots.policy: 0.496
  load_resource: 1472.262
  exclusion.robots: 0.517
  PetaboxLoader3.datanode: 234.871 (5)
*/